-- MySQL Script generated by MySQL Workbench
-- Sun Jun 24 18:45:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exams
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exams` DEFAULT CHARACTER SET utf8 ;
USE `exams` ;

-- -----------------------------------------------------
-- Table `exams`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Professors` (
  `idProfessors` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfessors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Courses` (
  `idCourses` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCourses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Professors_has_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Professors_has_Courses` (
  `professor_id` INT NOT NULL,
  `course_id` INT NULL,
  PRIMARY KEY (`professor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Exams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Points_Per_Question` INT NULL,
  `title` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Questions` (
  `idQuestions` INT NOT NULL AUTO_INCREMENT,
  `Question` VARCHAR(45) NULL,
  `Ans1` VARCHAR(45) NULL,
  `Ans2` VARCHAR(45) NULL,
  `Ans3` VARCHAR(45) NULL,
  `Ans4` VARCHAR(45) NULL,
  `Questionscol` VARCHAR(45) NOT NULL,
  `level` INT NULL,
  PRIMARY KEY (`idQuestions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Models` (
  `idModels` INT NOT NULL AUTO_INCREMENT,
  `Questions` TEXT NULL,
  `exam_id` INT NULL,
  PRIMARY KEY (`idModels`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Students` (
  `idStudents` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Year` VARCHAR(45) NULL,
  `Department` VARCHAR(45) NULL,
  `UserName` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudents`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Courses_has_Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Courses_has_Students` (
  `course_id` INT NOT NULL,
  `studenst_id` INT NOT NULL,
  PRIMARY KEY (`course_id`, `studenst_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
