-- MySQL Script generated by MySQL Workbench
-- Sun Jun 24 17:59:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exams
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exams` DEFAULT CHARACTER SET utf8 ;
USE `exams` ;

-- -----------------------------------------------------
-- Table `exams`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Professors` (
  `idProfessors` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfessors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Courses` (
  `idCourses` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCourses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Professors_has_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Professors_has_Courses` (
  `Professors_idProfessors` INT NOT NULL,
  `Courses_idCourses` INT NOT NULL,
  PRIMARY KEY (`Professors_idProfessors`, `Courses_idCourses`),
  INDEX `fk_Professors_has_Courses_Courses1_idx` (`Courses_idCourses` ASC),
  INDEX `fk_Professors_has_Courses_Professors_idx` (`Professors_idProfessors` ASC),
  CONSTRAINT `fk_Professors_has_Courses_Professors`
    FOREIGN KEY (`Professors_idProfessors`)
    REFERENCES `exams`.`Professors` (`idProfessors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_has_Courses_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `exams`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Exams` (
  `id` INT NOT NULL,
  `Points_Per_Question` INT NULL,
  `title` TEXT NULL,
  `Courses_idCourses` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Exams_Courses1_idx` (`Courses_idCourses` ASC),
  CONSTRAINT `fk_Exams_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `exams`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Questions` (
  `idQuestions` INT NOT NULL,
  `Question` VARCHAR(45) NULL,
  `Ans1` VARCHAR(45) NULL,
  `Ans2` VARCHAR(45) NULL,
  `Ans3` VARCHAR(45) NULL,
  `Ans4` VARCHAR(45) NULL,
  `exam_id` INT NULL,
  `Questionscol` VARCHAR(45) NOT NULL,
  `level` INT NULL,
  PRIMARY KEY (`idQuestions`),
  INDEX `fk_exam_id_question_idx` (`exam_id` ASC),
  CONSTRAINT `fk_exam_id_question_id`
    FOREIGN KEY (`exam_id`)
    REFERENCES `exams`.`Exams` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Models` (
  `idModels` INT NOT NULL,
  `Questions` TEXT NULL,
  `exam_id` INT NOT NULL,
  PRIMARY KEY (`idModels`),
  INDEX `fk_exam_id_model_idx` (`exam_id` ASC),
  CONSTRAINT `fk_exam_id_model`
    FOREIGN KEY (`exam_id`)
    REFERENCES `exams`.`Exams` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Students` (
  `idStudents` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Year` VARCHAR(45) NULL,
  `Department` VARCHAR(45) NULL,
  `UserName` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudents`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exams`.`Courses_has_Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exams`.`Courses_has_Students` (
  `Courses_idCourses` INT NOT NULL,
  `Students_idStudents` INT NOT NULL,
  PRIMARY KEY (`Courses_idCourses`, `Students_idStudents`),
  INDEX `fk_Courses_has_Students_Students1_idx` (`Students_idStudents` ASC),
  INDEX `fk_Courses_has_Students_Courses1_idx` (`Courses_idCourses` ASC),
  CONSTRAINT `fk_Courses_has_Students_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `exams`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Students_Students1`
    FOREIGN KEY (`Students_idStudents`)
    REFERENCES `exams`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
